version: "3.9"

services:
  db_test:
    image: postgres:15
    container_name: db_test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"
    tmpfs:
      - /var/lib/postgresql/data
