version: "3.9"

services:
  # === Desenvolvimento ===
  app_dev:
    build: .
    container_name: growtwitter_app_dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@growtwitter_db_dev:5432/growtwitter?schema=public
    volumes:
      - .:/app
    depends_on:
      - db_dev
    command: ["/usr/local/bin/docker-entrypoint.sh"]
    networks:
      - dev_network

  db_dev:
    image: postgres:15
    container_name: growtwitter_db_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: growtwitter
    ports:
      - "5432:5432"
    volumes:
      - growtwitter_postgres_data:/var/lib/postgresql/data
    networks:
      - dev_network

  # === Testes ===
  app_test:
    build: .
    container_name: growtwitter_app_test
    env_file:
      - .env.test
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@growtwitter_db_test:5432/growtwitter_test?schema=public
    volumes:
      - .:/app
    depends_on:
      - db_test
    command: ["/usr/local/bin/docker-entrypoint.sh"]
    networks:
      - test_network

  db_test:
    image: postgres:15
    container_name: growtwitter_db_test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: growtwitter_test
    ports:
      - "5433:5432"
    volumes:
      - growtwitter_postgres_test_data:/var/lib/postgresql/data
    networks:
      - test_network

volumes:
  growtwitter_postgres_data:
  growtwitter_postgres_test_data:

networks:
  dev_network:
  test_network:
