version: "3.9"

services:
  db_dev:
    image: postgres:15
    container_name: db_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_db
    ports:
      - "5433:5432"
    volumes:
      - dev_data:/var/lib/postgresql/data

volumes:
  dev_data:
