version: "3.9"

services:
  # ===== Desenvolvimento =====
  app_dev:
    build: .
    container_name: growtwitter_app_dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db_dev:5432/growtwitter?schema=public
    volumes:
      - .:/app
    depends_on:
      - db_dev
    command: sh -c "npx prisma generate && npm run dev"

  db_dev:
    image: postgres:15
    container_name: growtwitter_db_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: growtwitter
    ports:
      - "5432:5432"
    volumes:
      - growtwitter_postgres_data:/var/lib/postgresql/data

  # ===== Testes =====
  app_test:
    build: .
    container_name: growtwitter_app_test
    env_file:
      - .env.test
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@db_test:5432/growtwitter_test?schema=public
    volumes:
      - .:/app
    depends_on:
      - db_test
    command: sh -c "npx prisma generate && npm run test:docker"

  db_test:
    image: postgres:15
    container_name: growtwitter_db_test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: growtwitter_test
    ports:
      - "5433:5432"
    volumes:
      - growtwitter_postgres_test_data:/var/lib/postgresql/data

volumes:
  growtwitter_postgres_data:
  growtwitter_postgres_test_data:
